### ISSUE TITLE
Multithreaded compiling

### ISSUE THREAD

**Issue by cyberjunk** [Meridian59/Meridian59#244]
Is there any reason the nmake build environment is not doing a multithreaded build when compiling?

I know there are a few, but I don't think in this case? 
Otherwise I would recommend changing this in common.mak:

From:
CCOMMONFLAGS = -nologo -DBLAK_PLATFORM_WINDOWS -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE \
-TP -WX -GR- -EHsc- 

To:
CCOMMONFLAGS = -nologo -DBLAK_PLATFORM_WINDOWS -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE \
-TP -WX -GR- -EHsc- /MP 

Notice the /MP at the end.
Sorry I was too lazy to create a fork and pullrequest for that.

**Comment by Meridian59** [comment]
I think that -MP is not safe for building blakod because blakcomp does read-modify-write on kodbase.txt.  If it works, it's only by chance. 

We could turn it on for the C code, though.

**Comment by CyberBill** [comment]
I'm in the process of making Visual Studio 2013 project files that can correctly compile, link, and run the server and client.  So far I've got BlakServ working!

**Comment by Daenks** [comment]
Please see: Daenks/Meridian59_103#421

I have everything working under VS2008 as a solution. It builds all components successfully.

It should upgrade pretty flawlessly to VS2013, There are a few changes that have been made since then to how both repositories are compiled. I will update this pull when I can, or one of you can if it would be helpful to you.

**Comment by Meridian59** [comment]
Parallel compiling has been on for awhile now.
