### ISSUE TITLE
[General] Reagents must be in a stack of a certain size or greater to pen.

### ISSUE THREAD

**Issue by Kopfz** [Meridian59/Meridian59#270]
Only pen reagents when they are in a stack greater than certain quantity. That quantity should be easily changed for game balance, and quick response to exploitation.

For example: 
If a player is running around with 1 of every reagent type, only the stacks with >20 would be considered valid options for a penalty.

**Comment by jrotunda** [comment]
@davidklaw This is a good one - any thoughts on implementing this kind of change? 

This is small but effective for making pens a little tighter, a pen victory (harder than you think!) will feel better and be less cheesy.

**Comment by davidklaw** [comment]
I looked at this a bit and today's penalty logic grabs the inventory count, then starts randomly dropping items depending, the number of which depends on where their penalty counter stands.

If we still believe this should be considered, I'd love to hear ideas, but otherwise I think we can close this issue.
