### ISSUE TITLE
Stats reroll

### ISSUE THREAD

**Issue by Battlecat1337** [Meridian59/Meridian59#298]
1. Due to many school updates and other updates in general, stats preferences do shift
2. People need to have multiple chars with just small stats differences to use all the possible builds    which leads to chartrains and toon spaming
3. New or unexperiences playes still need 6-12 Month to max a char and often realise that they have chosen the wrong stats... frustrating them.

To solve all these issues my idea is to provide a reroll process for stats:

-should be expensive (~250k sh) and should only allow to switch 10-20 stat points
-should be only possible once a year
-yes you can learn a new school with 20 more int but it should be fine with the other rules mentioned above
-some fresh air, players will have fun to "optimise" their older chars

**Comment by jrotunda** [comment]
This is an unclear “issue” and an unsure that this kind of change solves an actual problem so much as introduces complicated new stat mechanics that no one is asking for other than a handful of bored players who maybe should make a new character instead of being able to “master everything” with 1 as this suggest.

 Suggest this be closed unless there is a specific design that explains some context.
