### ISSUE TITLE
NPC chatter breaks all the time

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#30]
The NPC chatter system (manually loading a set of commands from a text file) is brittle; on the public servers, NPC chatter seems to stop often.  Fix this so that it's permanently on.

**Comment by jrotunda** [comment]
A Zaphod request! 

We've come full circle now- The chatter broke a few times since. Fixed two years ago, 101 only, lost again, and the change to dlg file on your side. 

In case you want to document anything from the last time - otherwise....maybe good to close now?

Do we have what we need now to fix or stop it going forward or is there some testing we can do sometime?

**Comment by akirmse** [comment]
This is certainly in better shape.  If the dialog stops again, it can be repaired via the instructions in dialogconvert.py, which I wrote to convert the .tab files (which we had) into a text file with admin commands (which was apparently never checked in before).

```
# Convert from .tab file format to a sequence of admin commands.
# After recreating the world, e.g. "send o 0 recreate all" (or at initial startup),
# add NPC dialog to the speech library with these commands:
#
# python dialogconvert.py npc1.tab dialog.txt
#
# Blakserv admin command:
# read dialog.txt (file needs to be in server run directory)
```
