### ISSUE TITLE
Sorry, no other way of contacting you, so here it is

### ISSUE THREAD

**Issue by darkhog** [Meridian59/Meridian59#343]
I cannot access the website. it timeouts for me. However I can access it via proxy. WTF?! Tried to contact you via e-mail, but your e-mail server decided to timeout as well.

-- Dariusz "Darkhog" G. Jagielski, fan of the game from Poland.

**Comment by CyberBill** [comment]
This sort of thing typically happens when a DNS entry is updated, and that update doesn't properly flush out the old value.

If you have a router with custom settings, check what its doing, and clear its DNS cache manually. Otherwise, reboot your router and your computer. You can also try running ipconfig /flushdns from a command prompt (Windows).

If you're unlucky enough that the issue is your ISP (RARE), you'll have to call them. You can also change your computer to use 8.8.8.8 or another valid dns server.

I was once working on a large scale video streaming app, and we had all of Beijing unable to connect because most of the city is behind a NAT that cached the wrong DNS entry. It took a month to resolve!

-----Original Message-----

**Comment by akirmse** [comment]
The Web site is definitely up.  It does sound like you're having network problems.

**Comment by darkhog** [comment]
I know it's up. That's why I can browse it via proxy. But can't reach it without. Can you check with your hosting provider? I had issues with some hosts blocking Polish IP addresses either on purpose or by accident in the past. I've already tried all the things CyberBill suggested, save for calling my ISP (which is rather a professional one, one of the biggest Polish ISPs, UPC) and none of these have worked.

Another thing that I've just tried was to find an proxy that allows to impersonate IP from certain country and following countries seems to be blocked as well:
- Russia
- Czech Republic
- Slovakia

**Comment by akirmse** [comment]
I got this back from our ISP:


Certain IP ranges get blocked due to non-stop excessive hacking attempts on our servers and unfortunately it is the only way to stop the attacks.

I have removed these blocks to restore access, but future hacking attempts may cause them to be blocked again.

**Comment by darkhog** [comment]
By "hacking" you probably mean ddos. Ever heard about CloudFlare?
Dnia 26 września 2016 23:57 Andrew Kirmse &lt;notifications@github.com&gt; napisał(a):
I got this back from our ISP:Certain IP ranges get blocked due to non-stop excessive hackingattempts on our servers and unfortunately it is the only way tostop the attacks.I have removed these blocks to restore access, but future hackingattempts may cause them to be blocked again.—
