### ISSUE TITLE
Add New KOD

### ISSUE THREAD

**Issue by SilenceM59** [Meridian59/Meridian59#345]
Ok so I feel like a real newb right now, or maybe my copy of blakston hates new KOD files.

Here are my steps for testing the creation of a new KOD item so it can be available in the game. 

I started with something simple... a new bow.

1. Found the bow folder where long bow is at... I have a KOD and LKOD file (LKOD for extra languages it looks like).
2. I copied the longbow.kod file to evilbow.kod
3. I copied longbow.lkod to evilbow.kod
4. I edited both KOD files and renamed anything that says Long to Evil. 
5. I looked at both files I created, there are no Resource Names duplicated from other KOD files.
6. I updated util/system.khd and put the item after MagicBow in the Weapons list (name exactly as inside my KOD file).
6. I update the makefile and add the new BOF file name evilbow.bof
7. *** I then perform the `nmake debug=1` command  (was this my mistake?)
8. I then opened Blakserv.
9. For giggles I hit save, reload, save, close, reopen, re-nmake, reopen, resave, rebuild, close, reopen... 
10. I also copied the new rsb strings file from my blakserv rsc folder to my client.
11. I also see the rsc files for the bow in the run/rsc folder where my updated rsb strings file is.

..... No luck!

I've added 2 new bows, I can't get the game to recognize any of them. 

In DM I type:  dm get item evil bow
It says "there's nothing like this in the lands of Meridian".

I type:  dm get weapons
I only get the ones already in the game, even though I've tried adding my new bof to the beginning and end of the makefile bof list. 

Any help would be appreciated on this process.

**Comment by SilenceM59** [comment]
To help speed things up, here are all the files I touched... I tried uploading the KOD / LKOD Files but Github doesn't support them - sorry for the zip.

KOD Files for Evil Bow: [evilbow.zip] includes `makefile`
[evilbow.zip](https://github.com/Meridian59/Meridian59/files/1772268/evilbow.zip)

System file update: (util)
[util.zip](https://github.com/Meridian59/Meridian59/files/1772259/util.zip)

**Comment by SilenceM59** [comment]
I also did a full NotePad++ search for:

 - MagicBow   (case insensitive)
 - Magic Bow  (case insensitive)

The only places it popped up were places I had added EvilBow.

Is there a number somewhere I need to update like bow.bof "MAX_NUMBER_BOWS" or anything like that?

**Comment by akirmse** [comment]
A few things:

- Since you are getting lkod output files, it sounds like you're not using
the open source Blakod. I think that was added by another team in their own
fork.  I highly suggest not mixing forks.

- Just adding a new class doesn't affect the "dm" commands.  I'm not too
familiar with this code, but if you look at dm.kod, it appears to get the
list of items from RecreateItemTemplates in system.kod.  You'd need to
modify that code, rebuild in the kod directory, then reload in the server.

**Comment by SilenceM59** [comment]
dm.kod.

Thanks for letting me know! I am wondering why my search didn't get anything from there.

I appreciate you getting back to me.

**Comment by SilenceM59** [comment]
Are there any other places you can think of I need to change?

Does the `nmake debug=1` satisfy building everything or is there a step process?

I noticed there's a `kod/copynew.bat`

What steps "after" I have created the KOD files do I need to take in order to get them to be recognized in the game? Also do any files need to get pushed over to the game itself other than the RSB string file?

**Comment by Daenks** [comment]
When you add new classes to the game, in order for the global lists to be updated in a saved game (for example to make 'dm item item_name" work) you typically need to perform a "recreateall" message on the system. You can do this from the server console or the admin window in game with "send class system recreateall". This only applies if you are loading a saved game, as this is done automatically when a new game world is created. 

Also Andrew is correct to state that you seem to be using the open meridian fork, or one of it's other forks. It could get really messy if you mix and match between the two, even though most things are compatible.

**Comment by GarAdminTools** [comment]
just said the same thing in discord, it's probably recreateall

**Comment by SilenceM59** [comment]
Thanks so much guys!

`send o 0 recreateall`

This did the trick.

**Comment by SilenceM59** [comment]
BTW - On my server I stoled Daenks account cuz I couldn't figure out how to make a Creator account <3 sorry Daenks. If you want it back, let me know LOL

You guys are the best, thank you so much for helping. Now I can make black qor bows that drip acid and throw area blind effects for short periods of time. I mean, I probably won't get to half of these things, but I can dream right :)

PS: My first Meridian memory was when it first launched, everyone gathered in Marion to fight fungus beasts with a guide.

Who knows it might have been one of you guys!

**Comment by SilenceM59** [comment]
Anyways, I hope I won't bug you guys too much. When my server goes up (eventually) your god accounts will be waiting for ya!

**Comment by Daenks** [comment]
That account creator is free under copyleft license. Use at your leisure.

On Mar 1, 2018 2:56 PM, "Silence" <notifications@github.com> wrote:

BTW - On my server I stoled Daenks account cuz I couldn't figure out how to
make a Creator account <3 sorry Daenks. If you want it back, let me know LOL

You guys are the best, thank you so much for helping. Now I can make black
qor bows that drip acid and throw area blind effects for short periods of
time. I mean, I probably won't get to half of these things, but I can dream
right :)

PS: My first Meridian memory was when it first launched, everyone gathered
in Marion to fight fungus beasts with a guide.

Who knows it might have been one of you guys!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Meridian59/Meridian59/issues/345#issuecomment-369727932>,
or mute the thread
