### ISSUE TITLE
Bug: Multiple song resources played simultaneously causes the client to crash.

### ISSUE THREAD

**Issue by qorkod** [Meridian59/Meridian59#380]
With music ON in the client, if a room has one song playing from when the user loaded into the room and a new song it played over it, the game will crash after the second song finishes and original song restarts.

To reproduce, load Meridian with the music on. When you land in a room with music playing, cast any Jala spell (use a Jala Necklace for ease) to start a new song.

Zone in out of the room or let the two songs finish playing.

You can also cause this crash by sending a music resource to immediately play for a user or the online user class. Anyone with music on will crash.

The expectation is for a song to stop playing and for a second song to fade in and make it impossible for two music resources to play simultaneously.

When the Jala spell or second song ends for the first time per that user, the original song should fade back in.

**Comment by davidklaw** [comment]
I'm unable to reproduce this issue locally. I see that there are mp3 resources, but my log is showing missing midis, so I grabbed a couple Jala midis and renamed them to `smithy.mid` and `song11.mid` as I'm testing by casting Invigorate inside Fehr'loi Quan's shop. I zone into the shop, which is playing `smithy.mid` and cast Invigorate. The room music is replaced by the Jala song. When the Jala song ends, the room music continues. No crashes here.

Perhaps this has something to do with lower resource machines?

**Comment by jrotunda** [comment]
The original issue suggesting the causes of this crash explains is too many songs being played - the audio overlap when the songs begin and end is a separate bug of its own.

For the resource error and crash:

When a Jala song is played by a user, the active enchantments in the pi_room enchantment list of a room object is updated like any area effect. 

During a special case scenario (I'm debugging the exact trigger) - when the active object (user) who created the song is no longer in the room, the enchantment timer turns negative and causes the enchantment to become a permanent enchantment, but in an unnatural way that causes a resource update error - perhaps due to the two music resources conflicting - which leads to a crash when ANY NEW active users enter the room and hits YES in the resource update active dialogue window that pauses their gameplay (B1 Level).

At its best, the bug allows a Jala spell to stay up indefinitely. At its worst it causes nonstop resource errors, gameplay interruptions and crashing. 


The following 4 points are all bad:

This bug occurs for all users regardless of their hardware as it's a resource error. 

It can and has been activated by a user or two who know the correct steps to cause disruption. 

On its own, it occurs often out or volume of use, Jala is popular these days as veteran players have been able to invest in more advanced end game characters. 

It usually occurs in high traffic building areas like CV and always requires administrative intervention to fix.

**Comment by qorkod** [comment]
To update with better repro steps
