### ISSUE TITLE
Room: Gameplay: Avar Village: Safe spots and monster gen points allow for risk-free money-making

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#471]
In the Avar Village (kd4), when first entering the room the entire ledge the player can stand on, which takes up nearly half the area of the room has no spawn points, and all the spawns points for the monsters are on the ground level.

Since the ledge is so high, the monsters have no way of getting up to the ledge, and the avar chieftains, despite having range, can't fire their arrows at the players from there, and Avar Shaman can't target them, and can only use the occasional area spell (earthquake, sandstorm) as their minimal allowed mana allows.

Players take advantage of this spot, along with the new ability of selling bows to Wulfgang (this is ridiculous TBH and its own problem), to power-game and make far more money than is reasonable compared to other areas in Meridian, and make it difficult to maintain economy, and allow for power-gamers, with tons of mules, to simply use up the room and gain exorbitant amounts of shillings, eradicating any sense of resource management or survival which is inherently crucial to both the economic and competitive balance of Meridian.

There are other bad safe spots, but this is the worst one.

Expectation:

The Avars should be able use their distance attacks while they're being attacked - the players do not get hit AT ALL by them here unlike other safe spots (beach, castle brax) where they can at least fight back.

The Avars should be able to make their way onto the ledge and/or spawn on the ledge and kill those terrible looking walls of risk-free mules.

The ledge to be used as a distance spot for your bow, but still at a risk like any other location.

Reproduce:

- Go to the Avar Village (go rid_kd4)
- Stand on top of the ledge, to the East/Right of the room.
- Aggro the Avars by shooting at them with any range attack.
- Note that the Avars pile against the wall and do not pathfind their way up the ledge.
- Note that the Avars can't use their range attacks from this location.

Note:

_Currently on 101, new spawn points were added to allow monsters to spawn closer here and add some danger, but the ledge/unable to fire up issues remains._

**Comment by CardiovascularMike** [comment]
I suspect that the Chieftains not shooting up towards the ledge may have to do with the @LineOfSight method.  I believe this is true because the same thing happens with Chieftains if you stand on top of their tiny little 'houses' - they can't shoot you.

The chieftain will only shoot if:

1. It is actively aggressive towards a player
2. It succeeds a 1 in 6 roll check each time it has an opportunity to attack
3. It is within it's SPELL_RANGE_SQUARED
4. It has line of sight == True

I don't see where line of sight is defined.  It is also called in the Monster.KOD as a message / method.

I don't recommend changing points 1-4 above.  Additionally, changing line-of-sight implementation may have other potentially problematic effects - for example the Orc caves have lots of spot where a Shadowbeast could hit you but doesn't due to you being on a ledge.  This is good because Shadowbeasts do impressive damage and would be picking off new players often.

I do think a change is needed here as this room does disrupt the normal economy.  There is no reason for established players to sell goods ever because any time spent gathering those goods to sell to players would be better spent on this screen.  Why sell a few hours worth of acquired BDS when you could spend 30 minutes and get the same number of shillings?

I wish I knew what the answer is for this but I can't come up with something that can be implemented, that isn't cheesy, and/or doesn't result in the room be hugely dangerous (remember there is a mana node there).

I guess one solution:  Add a new condition to check if the chieftain is in room rid_kd4 and then set the conditions to shoot to something like:
Shoot if:

1. Is aggressive
2. Is within RANGE
3a. Succeeds roll check (1 in 6 chance) OR
3b Is in RID_KD4 AND Succeeds new roll check (1 in 12 chance - half as often as when they can see you)

If 3b results in an attack send a message to the player:  "The Avar chieftain expertly targets you with a high arcing shot from his long bow!"

**Comment by jrotunda** [comment]
To fix:
Since writing this issue, I've added two new GEN points to the map on the cliff which will cause an occasional monster, allowing users to still enjoy the map but also make it so they won't have a risk-free encounter, or encourage automated building tactics (botting)

To fix the issue, these gen points need to be added to ke4.Kod.
