### ISSUE TITLE
Izzio's purchase success message triggers incorrectly

### ISSUE THREAD

**Issue by davidklaw** [Meridian59/Meridian59#509]
When buying items from Izzio that you cannot carry, he will correctly state that you can't carry them but also incorrectly act as if you had a successful purchase.

From the chat log:
> Izzio says, "I'm unable to give you the mushrooms.  Perhaps you carry too much?"
> Izzio says, "Thanks!  May that bring you good health and wealth."

The expected behavior is that he tells you you're unable to carry them when you can't, and thanks you when you can (and makes the transaction of course).

**Comment by akirmse** [comment]
The issue is here:
https://github.com/Meridian59/Meridian59/blob/d752efdeee1b1da59284e44bd18ae55a56bd035c/kod/object/active/holder/nomoveon/battler/monster.kod#L3851
https://github.com/Meridian59/Meridian59/blob/d752efdeee1b1da59284e44bd18ae55a56bd035c/kod/object/active/holder/nomoveon/battler/monster.kod#L3873

ItemBoughtHook is called even when the buyer can't hold the items.  But the fix might not be as simple as returning in that case, because there's a loop over all the items being bought, and we have to be sure the right thing happens if only some of the items can be held.

**Comment by davidklaw** [comment]
Maybe this is a messaging change instead. Izzio is the only NPC to implement this hook and the issue is that his response is positive. Perhaps it should be neutral. Or nothing at all? Seems like Izzio would benefit from some random sayings instead to add some personality. Maybe a few like:

> You there, come take a look at my pack. You never know what you might find.
> Travel safely, and may you find what you seek.
> The earth provides, but a little coin never hurt. Care to trade?
> I’ve walked many paths, and each one led to something worth selling.
