### ISSUE TITLE
Error message(s) that occur during save + exit with people logged in

### ISSUE THREAD

**Issue by Aesica** [Meridian59/Meridian59#590]
Whenever a server save + exit happens while 1 or more players is logged on, the following errors are shown in the server console when it is next started:

![image](https://github.com/Meridian59/Meridian59/assets/22806592/b1a2e400-4400-49b9-b8ac-1255f1deb502)
![image](https://github.com/Meridian59/Meridian59/assets/22806592/3526212c-e4c7-4cda-916f-fd92ad37858d)
![image](https://github.com/Meridian59/Meridian59/assets/22806592/ea1ba6ab-52cb-42b6-aea3-318690493894)

Saving and restarting the server without anyone logged in makes the error go away until another save + exit is executed with people logged in again.  It doesn't appear to be harmful, but a bug is a bug.

**Comment by akirmse** [comment]
After some debugging, I find that this is due to players being considered still logged in when the server exits, and then when it restarts, the following stack trace occurs:

Room::LeaveHold(#what=OBJECT 60) room.bof (1913)
User::UserLogoff() user.bof (714)
User::DisconnectSession() user.bof (849)
System::LoadedFromDisk() system.bof (878)

LeaveHold calls BreakTrance, which tries to send a message to the user's room.  The room hash table hasn't yet been created at this point, causing the error messages.

This seems like a very old and pretty basic problem.  Potential solutions:

- Move the creation of the hash tables earlier in System::LoadedFromDisk.  This seems potentially the safest, as the tables were added fairly late as an optimization, and so probably little depends on their order of creation.

- Log off people when the server exits.  Makes logical sense but not sure how safe it is.

- Some more explicit change to trance breaking.
