### ISSUE TITLE
NPC: Gameplay: KocatanTradeMaster (Wulfgang) buys all items and isn't supposed to

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#627]
In the "Remote Trading Post of Wulfgang zax'Ak", Wulfgang is intended to be a shady merchant who has secret items for sale, and purchases Nerudite as part of some underground network on Ko'catan that trades with the Avar.

Currently, he's buying ANYTHING, and has the same function as Roq - this allows players to sell all the garbage from the Avar Village and their bows and nerudite armor at prices almost as good as if they went to the Ko'catan Smith and Reagent Shop.

The Island Smith and Healer/Apothercary shop were specifically updated a few years ago to allow for better gameplay with less restrictive trading on the island, whereas before, you had to bring things back to the mainland or needed elusion, or an elusion mule, to make the most of your time there.

Wulfgang did not purchase everything from the players then. Something was updated that I can't discern in the code where he now buys anything, and this allows for excessive and game-breaking shilling gain.

Expectation:

Wulfgang only purchase nerudite ore, armor or swords from players on the island.

Suggest if he purchase other items he offer a very low price, or have a conditional that he only sells to outlaws (since he's an outlaw)

**Comment by Aesica** [comment]
1. Do you (or anyone else) remember roughly what he used to purchase?  I'm guessing somebody at some point during the early open source days pushed something through to make him buy anything, because he currently has no item filter in place.
2. His markup is currently set to the second highest (MERCHANT_EXPENSIVE) which isn't a great deal, but given the location relative to the avar village, it's definitely convenient and still worth it because of the time saved.  It could be changed to MERCHANT_RIPOFF, but that also affects both his buying and selling prices.  If that's a desired result, it's easy enough to do.  If setting an item filter is preferable, I don't think adjusting his buy/sell rate is necessary.

**Comment by akirmse** [comment]
There's been no change to this class since open source was released:

https://github.com/Meridian59/Meridian59/commits/819e3ada61f978f738dd949d36b6767315bfc179/kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcmerch.kod

**Comment by Aesica** [comment]
That's odd, I could've sworn he had some sort of buy list filter back during the 3do days.  Maybe I'm losing my mind then.

**Comment by Meridian59** [comment]
The 3DO days were a long time ago.  Open sourcing was only in 2012,
post-NDS.

**Comment by jrotunda** [comment]
Based on development notes explaining the change to ROQ being made from MERCHANT_NORMAL to MERCHANT_EXPENSIVE (which Wulfgang is), this seems consistent as they both buy everything. 

Between that, and Ssnce there doesn't seem to have been a hidden change done to him and it's not a huge issue right now, I'm okay with closing this.
