### ISSUE TITLE
[Geometry] Sweet Grass Prairies entrance to Jasper missing geometry

### ISSUE THREAD

**Issue by sicoderealm** [Meridian59/Meridian59#649]
![image](https://github.com/Meridian59/Meridian59/assets/7548210/e258f469-11e8-41c7-b398-7b7a9bb19c90)

**Comment by jrotunda** [comment]
This one is egregious.

**Comment by jrotunda** [comment]
Design Notes:

If anyone would like to do anything to this room other than the aforementioned missing textures, I wanted to pass along some notes about the layout and design as it may affect your work.

- This area is considered a "City Outskirts" region, which are used as exit routes of a city or village. 
- Players start in Jasper, Cor Noth, and Marion. 
- The two other starting cities, **Cor Noth** and **Marion**, have their inn entrances next or facing the city entrance/main gate.
- For Cor Noth this is "The Main Gates of Cor Noth" - which shows a lake formed by running water, a wide area to fight newbie mobs, with a main travel route used by a variety of player types, and easy to see and understand beginner mobs (baby spider and centipede). 
- Cor Noth's other exit is beginning of  The King's Way, which has the wandering NPC Izzio, (mostly giant rats) which has a tight forest maze, but easily walked through, or the player could follow the Cibilo Creek which opens to the rest of the King's Way (with Bei Naq on the his island) as it passes a large body of water.
- For Marion this is "West Merchant Way", baby spiders, giant rats, with running water, multiple elevations and again Izzio, with the main travel route (King's Way and Merchant Way's are the main travel and trade routes that connect Cor Noth, Barloque and Marion)
- Marion's other exit spits you out near the Temple of Shal'ille (Izzio is there too...)
- Jasper's main entrance, past the smithy, is the Lake of Jala's Song (Again Izzio) - the most visually impressive main gate area, various elevations, water, rocks, grass, and a main trail to Off the Beaten Path into King's Way, a Guild Hall balcony, giant waterfall, and shortcut/advanced route to the mountains/evil forest/badland/Tos areas.
- Sweet Grass Prairies is an exit from East Jasper that the play is pushed towards due to the placement of the Jasper Inn. The player will likely go here first, falling off the cliff and going to Deep Forest of Farol (which is next to Sweet Grass) or into Sweet Grass directly, around the corner.

Observations and feedback for these two 'back exits' that get used fairly often by new players to the game:
- Sweet Grass Praeries is one of the least used maps, players do not travel through it often intentionally, nor do newbies spend much time here.
- This room's name is a reference and memorial to the player Sweet Grass, who played Meridian 59 when it was first released.
- The layout is very tight and hard to navigate, but also 3x the size of other 'back exit/outskirts maps' - and you can't see where you are going or get a sense of where the exits may be - it is a maze for new players.
- The monster here - the groundworm larvae - is a good mob weak to mace fighting and drops touch spell reagents for newbies, and the implied rocky, mountain border environment suits fits the design and background lore.
- It contains a Flagpole for Soldiers, which if a newbie attacks, will definitely die and have a harder time to run than in an open space, and not that much for PvPers fighting there.
- The feel of the room does not match the name "Praerie", and it is not comfortable to navigate or fight in; as a room dedicated to a player and as a major first room new players see, it should have a more welcoming and open look and feel, allowing them to see at least one exit and have more space to run and fight - perhaps with less narrow forest corridors, taller/larger trees, more mountains in the background to give a sense of place/and scale (you are next to the mountains that become the Hills and Peak - this is the SouthEast 'edge' of the terrain that has been 'mapped' by Meridian (at this time...)
- This room is FLAT - like many early rooms. Other than the mountain/Jasper exit, the rest of the room wasn't changed. There are no slopes or even changes in elevation - yet this is not the 'flatlands'. This area could use hills, slopes, rocky terrain, etc to be a feature as it doesn't have water or anything bright and impressive - using the forest, sky and nearby mountains are instead the environment to make the player feel a part of.
- Additional design discussion: Could be edited and used for connective tissue in the SouthEast portion of this room to another Room (example and TBD; a non-portal Raza > Meridian pathway)
