### ISSUE TITLE
Magic items are absurdly rare and often quite weak

### ISSUE THREAD

**Issue by Gar103** [Meridian59/Meridian59#745]
With the upcoming magic item system, we will, for the first time, see the actual drop rate of magic items. I am quite certain that 99% of all magic scimitars, mystics, etc that have ever dropped went unseen because they're in a pile of scimitars et al dropped by the very same enemy. Only 'off' weapons are ever noticed (i.e. wait why did this skeleton drop an Axe? ahhh it's odd)

Digging into the magic item system, I have discovered that the spawning of magic items is not just incredibly convoluted, but incredibly unlikely as well. So rare, in fact, that the 'best' magic mod / weapon combinations might literally have never been created in 101's entire history. I'll do a quick summary.

Magic mod creation begins with an Item Attribute Chance in a monster's treasure file. This chance maxes out at 10 from the Lupogg King, but is almost always between 2 and 4 for most other mobs. This isn't out of 100, it's out of **400**. So, a given 'drop' from the Lupogg King has a 2.5% chance to be a magic modded item. The Lupogg King drops several items, so you've got a couple 2.5% chances.

However. Each treasure file also has a Difficulty Seed. This generally links, with some fuzziness, to an available mod pool. The only tier 10 attribute is Vampirism, so Lupogg King magic weapon drops are highly likely to be vamp. If that fails, it can drop into the tier 9 mod pool, with Blind, Bonk, Hold, Purge, GMT, and mystical energy.  Sure, great. But I'm not talking about those mods. It's easy to farm Thrashers chest for Blind and Hold weapons.

I'm talking about the _other_ magic mods. Colhorr, faction, ceremonial, guild hall, justice... these have only a 3% chance of being a Mystic Sword, and a 1% chance of rolling Crushing, the highest power. (Maces and Short Swords get 3 shots at power rolls, and Axes and Hammers get 2, which is why they are generally much stronger).

So we're looking at a 3% roll, then a 1% roll... and worse, these magic mods are generally not in tier 9 and 10. To get them, you have to fight monsters with weaker treasure profiles. If you want to target farm a Colhorr weapon, you should fight Daemon Skeletons. If you want to target farm a Ceremonial weapon, you should fight _regular skeletons._ These monsters drop less items per kill, and have much lower Item Att Chances.

Napkin math for a Crushing Colhorr mystic goes like this...

Choose 3 out of 400 for the Item Att Chance
Only 3 out of those 4 successes will stay in the right diff seed
Choose 1 out of 7 for the att type (from the available pool of mods)
Choose 1 out of 100 for power = 9
Choose 3 out of 100 for mystic sword base

Adjust for how many items daemons drop... roughly 4

To target farm a Crushing Colhorr mystic, you would expect to kill over **one million** Daemon skeletons. If you farmed for 2 hours a night, every night, killing one Daemon per thirty seconds, that would take you over 11 years.

Is this actually justified? These mods are so weak, players have never been certain whether they _even work._ In Colhorr's case, the mod had a truncated calculation that actually made it do almost nothing! Hold mystics are easier to get and are directly superior to a bit of damage or offense.

The proof is in the pudding on this one - all I have to do is ask you to think of these mods, and what you've actually seen in your years playing. Almost exclusively shitty maces, short swords, axes, and hammers, right? Maybe one or two surprisingly rolled scimitars. And how often did you ever actually use those? Never? Me neither.

This whole system has way too harsh RNG, for mods that barely do anything.

Thoughts?

**Comment by jrotunda** [comment]
The defaults on a test server or other servers aren't the same as on 101.  Example: by default, Magic items are under the value of 100. That isn't the case on production.

Magic Item drops get boosted during events. Right now, during the bonus event, I just got two unidentified items from the Lupogg King: a hold long sword and invisibility ring. The setting for boosting magic item drops only takes a little push to have it be noticeable.

Also, I'm not sure we want these items to be getting "farmed" by players. 

They're supposed to be found rarely, and randomly, by any player. You can find special weapons on trees and zombies too. There doesn't seem to be a shortage of these items and I haven't heard any negative feedback about them in the last decade. 

Players *were* confused about the Colhorr/Guild Hall/ etc damage and +to hit modifying items were working (which you addressed) or not because of miscommunication with a previous developer, and it was assumed they were not working, which then lead to gossip and hearsay becoming more powerful than actuality.
